# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Probabilistic Soft Logic
email: psl-users@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
   Probabilistic soft logic (PSL) is a machine learning framework for developing probabilistic models.
   PSL models are easy and fast, you can define them using a straightforward logical syntax and solve them with fast convex optimization.
   PSL has produced state-of-the-art results in many areas spanning natural language processing, social-network analysis, and computer vision.
   The PSL framework is available as an Apache-licensed, open source project on GitHub with an active user group for support.
baseurl: "/psl-website" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Social Media
twitter_username: LINQS_edu
github_username: linqs
youtube_channel: UCJjzqRLiAIa3qENUkzK0zMA
googleplus_group: "106422136513784453367"

# Custom settings.
minima:
  date_format: "%B %d, %Y"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
